- job:
    name: ansible-role-zuul
    parent: unittests
    run: tests/test.yaml
    post-run: tests/collect-logs.yaml
    required-projects:
      - name: openstack-infra/zuul
    roles:
      - zuul: openstack/ansible-role-zuul

- job:
    name: ansible-role-zuul-fedora-27
    parent: ansible-role-zuul
    nodeset: fedora-27

- job:
    name: ansible-role-zuul-ubuntu-bionic
    parent: ansible-role-zuul
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-zuul-ubuntu-xenial
    parent: ansible-role-zuul
    nodeset: ubuntu-xenial

- project:
    templates:
      - windmill-jobs-fedora-27
      - windmill-jobs-xenial
    check:
      jobs:
        - ansible-role-zuul-fedora-27
        - ansible-role-zuul-ubuntu-bionic
        - ansible-role-zuul-ubuntu-xenial
        - tox-linters
    gate:
      jobs:
        - ansible-role-zuul-fedora-27
        - ansible-role-zuul-ubuntu-xenial
        - tox-linters
