---
- job:
    name: ansible-role-zuul-base
    parent: unittests
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    post-run: tests/collect-logs.yaml
    roles:
      - zuul: openstack/ansible-role-zuul
    vars:
      zuul_user_group: zuul-test
      zuul_user_name: zuul-test

# Testing for zuul_install_method: pip
- job:
    name: ansible-role-zuul
    parent: ansible-role-zuul-base

- job:
    name: ansible-role-zuul-fedora-latest
    parent: ansible-role-zuul
    nodeset: fedora-latest

- job:
    name: ansible-role-zuul-ubuntu-bionic
    parent: ansible-role-zuul
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-zuul-ubuntu-xenial
    parent: ansible-role-zuul
    nodeset: ubuntu-xenial

# Testing for zuul_install_method: git
- job:
    name: ansible-role-zuul-src
    parent: ansible-role-zuul-base
    required-projects:
      - name: openstack-infra/zuul
    vars:
      zuul_git_update: false
      zuul_install_method: git

- job:
    name: ansible-role-zuul-src-fedora-latest
    parent: ansible-role-zuul-src
    nodeset: fedora-latest

- job:
    name: ansible-role-zuul-src-ubuntu-bionic
    parent: ansible-role-zuul-src
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-zuul-src-ubuntu-xenial
    parent: ansible-role-zuul-src
    nodeset: ubuntu-xenial

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
      - windmill-jobs-xenial
    check:
      jobs:
        - ansible-role-zuul-fedora-latest
        - ansible-role-zuul-ubuntu-bionic
        - ansible-role-zuul-ubuntu-xenial
        - ansible-role-zuul-src-fedora-latest
        - ansible-role-zuul-src-ubuntu-bionic
        - ansible-role-zuul-src-ubuntu-xenial
        - tox-linters
        - windmill-tox-molecule
    gate:
      jobs:
        - ansible-role-zuul-fedora-latest
        - ansible-role-zuul-ubuntu-bionic
        - ansible-role-zuul-ubuntu-xenial
        - ansible-role-zuul-src-fedora-latest
        - ansible-role-zuul-src-ubuntu-bionic
        - ansible-role-zuul-src-ubuntu-xenial
        - tox-linters
        - windmill-tox-molecule
